```{r}
df <- read_csv("C:/Users/saiph/Desktop/sem2/ait580/project/EV.csv")
```

```{r}

library(ggplot2)
library(dplyr)

```


```{r}
# Set the theme
theme_set(theme_minimal())

# Chart title
chart_title <- 'Number of Electric Vehicles Based on Target'

# Create a ggplot
ggplot(df, aes(x = `Electric Vehicle Type`, fill = `Electric Vehicle Type`)) +
  geom_bar() +
  labs(title = chart_title, x = 'Target', y = 'Number') +
  theme_minimal() +
  theme(legend.position = 'none') +  # No legend for this plot
  scale_x_discrete(labels = c('BEV', 'PHEV')) +  # Customize x-axis labels
  geom_text(
    aes(label = sprintf('%.1f%%', (..count.. / sum(..count..)) * 100)),
    stat = 'count',
    position = position_stack(vjust = 0.5),
    vjust = 1.5,
    size = 4
  )


```
Univarient analysis:
```{r}
library('ggplot2')
ggplot(df,aes(x=County))+
  geom_bar()+
  labs(title='County-wise EV Distribution')
```


```{r}
# Assuming you have 'Make' and 'Model' variables
ggplot(df, aes(x = Make)) +
  geom_bar() +
  labs(title = "Make Distribution")

# Repeat for Model
ggplot(df, aes(x = Model)) +
  geom_bar() +
  labs(title = "Model Distribution")

```

